### ISSUE TITLE
How to use env-file?

### ISSUE THREAD

**Issue by hueyless** [clem109/drone-wechat#1]
in yml file like 
env_file: myvars.env

not work

I want pass $(git log -1 --pretty=format:'%h|%an|%s) to $PLUGIN_DESCRIPTION

**Comment by clem109** [comment]
I'm not sure I fully understand, could you explain a bit in more detail perhaps with a yaml file example.

**Comment by hueyless** [comment]
https://discourse.drone.io/t/env-file-possible/1943 I found this, it says not supported
is there a way can send a file context as PLUGIN_DESCRIPTION to users? I can put the result of command "git log -1 --pretty=format:'%h|%an|%s" in the file.

**Comment by clem109** [comment]
@hweidz I think this is perhaps a drone related issue rather than this WeChat plugin. 

Have a look through this, https://github.com/drone/drone/issues/2223

Are you mounting you're env file in your docker container?

**Comment by hueyless** [comment]
/.env file seems EE-only

**Comment by clem109** [comment]
seems like it, I'm closing this issue 😄
